# SPDX-License-Identifier: GPL-2.0-only

mtk-camsv71-y := mtk_camsv71.o mtk_camsv71_hw.o mtk_camsv71_video.o
obj-$(CONFIG_VIDEO_MTK_CAMSV71) += mtk-camsv71.o

mtk-seninf71-y := mtk_seninf71.o mtk_seninf71_hw.o
obj-$(CONFIG_VIDEO_MTK_SENINF71) += mtk-seninf71.o
