# SPDX-License-Identifier: GPL-2.0
# The objects in this directory are built by the parent Makefile
# (fts_touch_spi-y lists them with explicit fts_lib/ paths), so kbuild never
# needs to descend into here.
