obj-$(CONFIG_CHARGER_CLASS)	+= charger_class.o
obj-$(CONFIG_MT6375_CHARGER)	+= mt6375-charger.o
obj-$(CONFIG_MT6375_BATTERY)	+= mtk-battery.o
mtk-battery-objs := mtk_battery_coulomb_service.o mtk_battery.o mtk_battery_algo.o mt6375-gauge.o
