# SPDX-License-Identifier: GPL-2.0

# platform driver
snd-soc-mt6895-afe-y := \
mt6895-afe-pcm.o \
mt6895-afe-clk.o \
mt6895-afe-gpio.o \
mt6895-dai-adda.o \
mt6895-afe-control.o \
mt6895-dai-i2s.o \
mt6895-dai-hw-gain.o \
mt6895-dai-pcm.o \
mt6895-dai-src.o \
mt6895-dai-hostless.o \
mt6895-dai-tdm.o \
mt6895-misc-control.o

obj-$(CONFIG_SND_SOC_MT6895) += snd-soc-mt6895-afe.o

# machine driver
obj-$(CONFIG_SND_SOC_MT6895_MT6368) += mt6895-mt6368.o
